export const PAIN_KEYWORDS = [
    // ── FRUSTRATION DIRECTE (EN) ──
    "i hate", "i hate this", "i hate when", "i hate how",
    "i hate that", "i hate having to", "i hate doing",
    "i'm frustrated", "so frustrated", "extremely frustrated",
    "frustrating as hell", "beyond frustrated",
    "i'm tired of", "so tired of", "tired of dealing with",
    "tired of manually", "tired of having to",
    "drives me crazy", "driving me crazy", "drives me insane",
    "drives me nuts", "it's driving me insane",
    "pain in the ass", "pain in the neck", "such a pain",
    "absolute nightmare", "it's a nightmare", "complete nightmare",
    "it sucks", "this sucks", "sucks so much", "sucks hard",
    "this is terrible", "this is awful", "this is horrible",
    "this is ridiculous", "this is insane", "this is absurd",
    "so annoying", "incredibly annoying", "super annoying",
    "drives me up the wall", "makes me want to",
    "unbearable", "unacceptable", "inexcusable",
    "kills me", "killing me", "it's killing my",

    // ── PROBLEME NON RESOLU (EN) ──
    "why is there no", "why is there still no",
    "why doesn't exist", "why doesn't anyone",
    "why hasn't anyone", "why hasn't someone",
    "nobody has solved", "no one has solved",
    "nobody has built", "no one has built",
    "there is no good", "there's no good",
    "there is no solution", "there's no solution",
    "there is no tool", "there's no tool",
    "there is no app", "there's no app",
    "there is no way", "there's no way",
    "no solution for", "still no solution",
    "still no way to", "still no tool",
    "why can't i", "why can't we",
    "why isn't there", "why aren't there",
    "impossible to find", "impossible to do",
    "can't find anything", "can't find a tool",
    "can't find a solution", "can't find software",
    "nothing exists for", "nothing out there for",
    "gap in the market", "market gap",

    // ── PERTE DE TEMPS (EN) ──
    "waste so much time", "wasting so much time",
    "waste hours", "wasting hours", "hours every day",
    "hours every week", "hours per week", "hours per day",
    "takes forever", "takes so long", "takes too long",
    "doing it manually", "done manually", "do it manually",
    "copy paste every", "copy pasting", "copy and paste",
    "manually every time", "manually each time",
    "repetitive task", "repetitive work", "repetitive process",
    "same thing every day", "same thing every week",
    "over and over", "again and again",
    "time consuming", "incredibly time consuming",
    "so much time on", "too much time on",
    "spend all day", "spending all day",

    // ── INTENTION DE PAYER (EN) ──
    "i'd pay", "i would pay", "i'd literally pay",
    "i'd pay anything", "i'd pay good money",
    "take my money", "shut up and take my money",
    "please someone build", "someone needs to build",
    "someone should build", "someone please make",
    "why hasn't someone built", "would pay for",
    "willing to pay", "would pay monthly",
    "need a tool", "need an app", "need a software",
    "need a platform", "need a service",
    "looking for a tool", "looking for software",
    "looking for an app", "looking for a solution",
    "is there a tool", "is there an app",
    "is there software", "is there a service",
    "does anyone know a tool", "does anyone know software",
    "recommend a tool", "recommend software",
    "recommend an app", "any good tool for",
    "any tool that", "any app that", "any software that",

    // ── OUTILS EXISTANTS MAUVAIS (EN) ──
    "every tool i've tried", "every tool i have tried",
    "tried everything", "tried every tool",
    "nothing works", "nothing works well",
    "all tools suck", "existing tools are terrible",
    "current tools are", "the tools out there",
    "way too expensive", "insanely expensive",
    "too expensive for", "overpriced", "rip off",
    "not worth it", "waste of money",
    "terrible support", "no customer support",
    "support is useless", "support never responds",
    "buggy", "full of bugs", "so many bugs",
    "keeps crashing", "crashes all the time",
    "slow as hell", "incredibly slow",
    "clunky", "so clunky", "super clunky",
    "outdated", "feels outdated", "looks outdated",
    "ui is terrible", "ux is terrible",
    "hard to use", "difficult to use",
    "not user friendly", "unintuitive",

    // ── AUTOMATISATION (EN) ──
    "is there a way to automate", "how do i automate",
    "can this be automated", "automate this",
    "want to automate", "trying to automate",
    "automate the process", "automate my workflow",
    "manual process", "still doing this manually",
    "still doing it manually", "doing everything manually",
    "has to be a better way", "there has to be a better way",
    "must be a better way", "better way to do this",
    "better way to handle", "better way to manage",
    "streamline this", "streamline the process",
    "workflow is broken", "broken workflow",
    "our process is terrible", "the process is awful",
    "such a hassle", "so much friction",
    "too many steps", "too many clicks",

    // ── FREELANCE / BUSINESS (EN) ──
    "clients never pay on time", "clients don't pay",
    "chasing invoices", "chasing payments",
    "late payments", "unpaid invoices",
    "scope creep", "clients keep changing",
    "onboarding is a mess", "onboarding takes",
    "reporting takes", "reporting is a nightmare",
    "contract management", "tracking hours is",
    "billing is a pain", "invoicing is painful",

    // ── FRUSTRATION DIRECTE (FR) ──
    "j'en ai marre", "j'en ai marre de", "j'en peux plus",
    "c'est chiant", "c'est trop chiant", "tellement chiant",
    "c'est galere", "quelle galere", "vraiment galere",
    "c'est nul", "c'est vraiment nul", "completement nul",
    "c'est horrible", "c'est terrible", "c'est insupportable",
    "c'est ridicule", "c'est absurde", "c'est scandaleux",
    "je deteste", "je deteste quand", "je deteste faire",
    "j'ai horreur de", "j'ai horreur quand",
    "me saoule", "ca me saoule", "vraiment saoule",
    "me fatigue", "ca me fatigue", "tellement fatigue de",
    "me gonfle", "ca me gonfle",
    "cauchemar", "un vrai cauchemar", "c'est un cauchemar",
    "impossible de", "impossible a", "impossible trouver",

    // ── PROBLEME NON RESOLU (FR) ──
    "pourquoi il n'existe pas", "pourquoi y'a pas",
    "pourquoi personne n'a", "personne n'a encore",
    "personne n'a resolu", "personne n'a fait",
    "pas de solution pour", "aucune solution pour",
    "pas d'outil pour", "aucun outil pour",
    "pas d'application pour", "aucune appli pour",
    "il manque un outil", "il manque une solution",
    "il devrait exister", "quelqu'un devrait creer",
    "quelqu'un devrait faire", "quelqu'un devrait developper",

    // ── PERTE DE TEMPS (FR) ──
    "perte de temps", "vraiment une perte de temps",
    "ca prend des heures", "des heures chaque jour",
    "des heures chaque semaine", "passe des heures a",
    "copier coller", "copier-coller", "copie colle",
    "fait manuellement", "faire manuellement", "tout a la main",
    "tache repetitive", "taches repetitives",
    "la meme chose chaque jour", "refaire la meme chose",
    "encore et encore", "toujours la meme chose",

    // ── INTENTION DE PAYER (FR) ──
    "je paierais", "je paierais bien", "je payerais",
    "pret a payer",
    "j'aimerais un outil", "j'aurais besoin d'un outil",
    "besoin d'une solution", "besoin d'un logiciel",
    "vous connaissez un outil", "vous connaissez un logiciel",
    "recommandez un outil", "recommander une appli",
    "il existe un outil", "il existe une appli",
    "cherche un outil", "cherche un logiciel",
    "cherche une solution", "cherche une application",

    // ── OUTILS EXISTANTS MAUVAIS (FR) ──
    "trop cher", "beaucoup trop cher", "vraiment trop cher",
    "hors de prix", "prix abusif", "arnaque",
    "les outils existants", "les outils actuels",
    "aucun outil ne fait", "aucun logiciel ne permet",
    "plein de bugs", "bugue", "ca bugue",
    "plante tout le temps", "ca plante",
    "lent", "tellement lent", "super lent",
    "pas intuitif", "difficile a utiliser",
    "interface nulle", "ux nulle",
    "support client nul", "support inexistant",

    // ── AUTOMATISATION (FR) ──
    "comment automatiser", "automatiser ca",
    "il faudrait automatiser", "on peut automatiser",
    "processus manuel", "encore manuel",
    "doit y avoir un meilleur moyen", "il doit exister une meilleure facon",
    "meilleure facon de", "meilleur moyen de",
    "trop d'etapes", "trop de clics",
    "workflow cassee", "notre process est nul",
]